// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { Application } from '@hotwired/stimulus'
import Dialog from '@stimulus-components/dialog'
import Clipboard from '@stimulus-components/clipboard'

const application = Application.start()
application.register('dialog', Dialog)
application.register('clipboard', Clipboard)