AllCops:
  NewCops: enable
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'config/routes.rb'
    - 'config/environments/*'
Metrics/MethodLength:
  Exclude:
    - '**/*'
Metrics/CyclomaticComplexity:
  Exclude:
    - '**/*'
Metrics/PerceivedComplexity:
  Exclude:
    - '**/*'
Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'
    - 'bin/*'